name: shartflix
description: "A clean architecture movie app for case study"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^7.6.4
  dartz: ^0.10.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  json_serializable: ^6.7.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sinflix_logo.png
    - assets/images/sinflix_splash.png
    - assets/icons/google_icon.png
    - assets/icons/facebook_icon.png
    - assets/icons/apple_icon.png
    - assets/backup_posters/
    - assets/icons/limited_offer/
    - assets/images/glow_effect_circle.png
